import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../constants/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.bgDark,
        paddingTop: Platform.OS === 'android' ? 30 : 0,
    },
    screenBase: { flex: 1, backgroundColor: COLORS.bgDark },

    // Splash
    splashContainer: {
        flex: 1,
        backgroundColor: COLORS.tealDark,
        alignItems: 'center',
        justifyContent: 'center',
    },
    splashDecoration: {
        position: 'absolute',
        top: -100,
        left: -50,
        width: '150%',
        height: '50%',
        backgroundColor: COLORS.tealMid,
        borderRadius: 1000,
        opacity: 0.3,
    },
    centerContent: { zIndex: 10, alignItems: 'center' },

    checkBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: COLORS.green,
        borderRadius: 20,
        padding: 4,
        borderWidth: 3,
        borderColor: COLORS.white,
    },
    splashTextContainer: { alignItems: 'center', marginTop: 40 },
    splashTitle: { fontSize: 36, fontWeight: 'bold', color: COLORS.white },
    splashSubtitle: { color: COLORS.tealLight, letterSpacing: 2, fontSize: 12 },
    dot: { width: 8, height: 8, borderRadius: 4 },
    footerContainer: { position: 'absolute', bottom: 40, alignItems: 'center' },
    footerText: { color: COLORS.tealLight, opacity: 0.8 },
    versionText: { color: COLORS.tealLight, opacity: 0.5, fontSize: 10 },

    // Auth
    authContainer: { flex: 1, backgroundColor: COLORS.tealDark },
    headerCurve: {
        height: '35%',
        backgroundColor: COLORS.tealMid,
        borderBottomRightRadius: 100,
        borderBottomLeftRadius: 100,
        position: 'absolute',
        width: '100%',
    },
    authContent: {
        flex: 1,
        justifyContent: 'center',
        padding: 30,
        paddingTop: 100,
    },
    authTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: COLORS.white,
        marginBottom: 5,
    },
    authSubtitle: { color: COLORS.tealLight, marginBottom: 40 },
    label: {
        color: COLORS.tealLight,
        fontSize: 10,
        textTransform: 'uppercase',
        fontWeight: 'bold',
        marginBottom: 5,
        marginLeft: 5,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.2)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.tealMid,
        paddingHorizontal: 15,
        height: 55,
    },
    input: { flex: 1, color: COLORS.white, fontSize: 16 },
    roleToggle: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        backgroundColor: 'rgba(0,0,0,0.2)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.tealMid,
    },
    toggleSwitch: {
        width: 40,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        padding: 2,
    },
    toggleKnob: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: COLORS.white,
    },
    primaryButton: {
        backgroundColor: COLORS.green,
        height: 60,
        borderRadius: 12,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
        shadowColor: COLORS.green,
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
    },
    primaryButtonText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },

    // Home
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 24,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.card,
        backgroundColor: COLORS.card,
    },
    headerTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.white },
    headerSub: {
        fontSize: 10,
        color: COLORS.gray,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.grayDark,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.gray,
    },
    streakBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(250, 204, 21, 0.1)',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(250, 204, 21, 0.3)',
        marginBottom: 24,
        justifyContent: 'center',
    },
    assetCard: {
        backgroundColor: COLORS.card,
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: COLORS.grayDark,
        marginBottom: 32,
    },
    cardLabel: { color: COLORS.gray, fontSize: 10, fontWeight: 'bold' },
    tag: {
        backgroundColor: 'rgba(37, 99, 235, 0.2)',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    tagText: { color: COLORS.blue, fontSize: 10, fontWeight: 'bold' },
    assetName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: COLORS.white,
        marginVertical: 8,
    },
    assetId: { color: COLORS.gray, marginBottom: 15 },
    assetRow: {
        flexDirection: 'row',
        gap: 20,
        borderTopWidth: 1,
        borderTopColor: COLORS.grayDark,
        paddingTop: 15,
    },
    startButton: {
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: COLORS.blue,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 6,
        borderColor: 'rgba(37, 99, 235, 0.3)',
        elevation: 15,
    },
    startButtonText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: COLORS.white,
        marginTop: 5,
    },
    startButtonSub: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 12,
        letterSpacing: 1,
    },
    sectionTitle: {
        color: COLORS.gray,
        fontSize: 12,
        fontWeight: 'bold',
        marginBottom: 15,
    },
    historyItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: COLORS.card,
        padding: 16,
        borderRadius: 12,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: COLORS.grayDark,
    },
    historyTitle: { color: COLORS.white, fontWeight: 'bold', fontSize: 14 },
    historyDate: { color: COLORS.gray, fontSize: 12 },

    // Manager
    statBox: {
        flex: 1,
        backgroundColor: COLORS.white,
        padding: 15,
        borderRadius: 12,
        borderLeftWidth: 4,
    },
    statLabel: {
        fontSize: 10,
        fontWeight: 'bold',
        color: COLORS.grayDark,
        textTransform: 'uppercase',
    },
    statValue: { fontSize: 28, fontWeight: 'bold' },
    fleetRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: COLORS.card,
        padding: 15,
        borderRadius: 12,
        borderLeftWidth: 4,
        marginBottom: 10,
    },
    rowTitle: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
    statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },

    // Forms & Inspection
    formInput: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.card,
        borderWidth: 1,
        borderColor: COLORS.grayDark,
        borderRadius: 8,
        paddingHorizontal: 15,
        height: 50,
    },
    footerAction: {
        padding: 24,
        borderTopWidth: 1,
        borderTopColor: COLORS.card,
        backgroundColor: COLORS.bgDark,
    },
    inspectionCard: {
        backgroundColor: COLORS.card,
        padding: 30,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.grayDark,
        minHeight: 250,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    cardCategory: {
        color: COLORS.blue,
        fontWeight: 'bold',
        fontSize: 10,
        textTransform: 'uppercase',
        marginBottom: 10,
    },
    cardTitle: {
        color: COLORS.white,
        fontSize: 26,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
    },
    cardDesc: { color: COLORS.gray, textAlign: 'center', lineHeight: 22 },
    guideLink: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 20,
        backgroundColor: 'rgba(37, 99, 235, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    actionBtn: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderRadius: 12,
        elevation: 3,
    },
    actionBtnTitle: { color: COLORS.white, fontSize: 18, fontWeight: 'bold' },
    actionBtnSub: { color: 'rgba(255,255,255,0.8)', fontSize: 12 },

    // Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.9)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#1a1a1a',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        height: '85%',
        borderTopWidth: 1,
        borderTopColor: COLORS.grayDark,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    aiBox: {
        backgroundColor: '#2a2a2a',
        padding: 15,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(37, 99, 235, 0.3)',
        marginBottom: 25,
    },
    aiInput: {
        backgroundColor: 'rgba(0,0,0,0.3)',
        color: COLORS.white,
        borderRadius: 8,
        padding: 10,
        height: 80,
        textAlignVertical: 'top',
        marginBottom: 10,
    },
    aiBtn: {
        backgroundColor: 'rgba(37, 99, 235, 0.15)',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(37, 99, 235, 0.5)',
    },
    aiBtnText: { color: COLORS.blue, fontWeight: 'bold', fontSize: 12 },
    aiResult: {
        marginTop: 10,
        padding: 10,
        borderLeftWidth: 3,
        backgroundColor: 'rgba(0,0,0,0.2)',
    },
    severityBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        borderRadius: 12,
        marginBottom: 10,
        gap: 15,
    },
    iconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // Summary
    summaryRing: {
        width: 120,
        height: 120,
        borderRadius: 60,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 6,
        backgroundColor: COLORS.card,
        marginBottom: 20,
    },
    summaryCard: {
        width: '100%',
        backgroundColor: COLORS.card,
        borderRadius: 12,
        padding: 15,
        marginBottom: 30,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.grayDark,
    },

    // Bottom Nav
    bottomNav: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: 15,
        backgroundColor: COLORS.card,
        borderTopWidth: 1,
        borderTopColor: COLORS.grayDark,
    },
});
